# Generated by Django 5.0.1 on 2024-02-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demomodel',
            name='title',
            field=models.CharField(default='Mr', max_length=2),
        ),
    ]
