# Generated by Django 5.0.2 on 2024-02-14 20:53

import FormsAdvanced.formdemo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formdemo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelone',
            name='name',
            field=models.CharField(max_length=10, validators=[FormsAdvanced.formdemo.models.validate_white_space]),
        ),
    ]
