# Generated by Django 5.0.2 on 2024-02-18 00:29

import FormsAdvanced.formdemo.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formdemo', '0002_alter_modelone_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelone',
            name='last_name',
            field=models.CharField(default='Dimitrov', max_length=10, validators=[FormsAdvanced.formdemo.models.validate_white_space, django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='modelone',
            name='name',
            field=models.CharField(max_length=10, validators=[FormsAdvanced.formdemo.models.validate_white_space, django.core.validators.MinLengthValidator(2)]),
        ),
    ]
