# Generated by Django 5.0.2 on 2024-02-19 22:39

import FormsAdvanced.formdemo.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formdemo', '0003_modelone_last_name_alter_modelone_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('job', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='modelone',
            name='last_name',
            field=models.CharField(max_length=10, validators=[FormsAdvanced.formdemo.models.validate_white_space, django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='modelone',
            name='name',
            field=models.CharField(max_length=10, validators=[FormsAdvanced.formdemo.models.validate_white_space, django.core.validators.MinLengthValidator(3)]),
        ),
    ]
