# Generated by Django 5.0.2 on 2024-02-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('age', models.IntegerField()),
                ('description', models.TextField(max_length=200)),
                ('sports', models.IntegerField(choices=[(1, 'football'), (2, 'basketball'), (3, 'box')])),
                ('interests', models.IntegerField(choices=[(1, 'Gaming'), (2, 'Reading'), (3, 'Drawing'), (4, 'Watching'), (5, 'Drafting')])),
                ('music', models.IntegerField(choices=[(1, 'Pop'), (2, 'Pop-folk'), (3, 'Metal'), (4, 'Rap')])),
            ],
        ),
    ]
